### ISSUE TITLE
Provide more complete example of JSON object for actor profile show action

### ISSUE THREAD

**Issue by andreas-venturini** [denkungsart/castupload-doc#13]
I've had to field some questions in the last weeks where some of our users requested a full json object structure (for actor profiles) - the example snippet we currently display is somewhat limited, so we should add all fields that we currently output in V1 of the API (this means also adding all available nested JSON objects), i.e.:

* add missing fields (this should not be too involved)
* `pictures` (at least two)
* `external_showreels`
* `showreels` (let's include at least two),
* `vita` (include full object -  and full examples for vita_types `primary_education`, `award`, `education`, `film` (include two entries here so users see an example for an array of hashes), `television` - the remaining vita_types should be included but can be empty arrays.

Fill out a profile locally with real values from a public profile (adapt e.g. from https://www.castupload.com/actors/adrian-topol)

**Comment by yoshih** [comment]
Can I use dummy URLs for pictures and external showreels? Something like "test.png".
