### ISSUE TITLE
Add picture attributes description

### ISSUE THREAD

**Issue by yoshih** [denkungsart/castupload-doc#7]
References https://github.com/denkungsart/castupload/pull/5388

Add a description for new profile picture attributes `year` and `recorded_at` to the API guide. Also explain how they depend on each other.

**Comment by andreas-venturini** [comment]
When doing this also add a full picture hash to the example JSON snippet we give for the actor profile show action.

**Comment by andreas-venturini** [comment]
closing in favor of GH-13
